# Generated by Django 3.1.2 on 2021-06-23 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kelas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idkls', models.CharField(blank=True, max_length=200, null=True)),
                ('namakls', models.CharField(blank=True, max_length=200, null=True)),
                ('spp', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Siswa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nis', models.CharField(blank=True, max_length=200, null=True)),
                ('nama', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Kelassiswa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idkls', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.kelas')),
                ('nis', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data.siswa')),
            ],
        ),
    ]
