# Generated by Django 3.1.2 on 2021-06-23 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dokumen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('document', models.ImageField(blank=True, null=True, upload_to='')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ortu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namaay', models.CharField(blank=True, max_length=200, null=True)),
                ('nikay', models.CharField(blank=True, max_length=200, null=True)),
                ('statusay', models.CharField(blank=True, choices=[('Masih Hidup', 'Masih Hidup'), ('Meninggal Dunia', 'Meninggal Dunia')], max_length=200, null=True)),
                ('alamatay', models.CharField(blank=True, max_length=200, null=True)),
                ('pendidikanay', models.CharField(blank=True, choices=[('Tidak Sekolah', 'Tidak Sekolah'), ('SD/MI', 'SD/MI'), ('SMP/MTS', 'SMP/MTS'), ('SMA/MA/SMK', 'SMA/MA/SMK'), ('Diploma', 'Diploma'), ('S1', 'S1'), ('S2', 'S2'), ('S3', 'S3')], max_length=200, null=True)),
                ('pendapatanay', models.CharField(blank=True, choices=[('0 - 500.000', '0 - 500.000'), ('500.000 - 1.000.000', '500.000 - 1.000.000'), ('1.000.000 - 3.000.000', '1.000.000 - 3.000.000'), ('3.000.000 - 5.000.000', '3.000.000 - 5.000.000'), ('5.000.000 - 10.000.000', '5.000.000 - 10.000.000'), ('10.000.000 ++', '10.000.000 ++')], max_length=200, null=True)),
                ('nohpay', models.CharField(blank=True, max_length=200, null=True)),
                ('namaib', models.CharField(blank=True, max_length=200, null=True)),
                ('nikib', models.CharField(blank=True, max_length=200, null=True)),
                ('statusib', models.CharField(blank=True, choices=[('Masih Hidup', 'Masih Hidup'), ('Meninggal Dunia', 'Meninggal Dunia')], max_length=200, null=True)),
                ('alamatib', models.CharField(blank=True, max_length=200, null=True)),
                ('pendidikanib', models.CharField(blank=True, choices=[('Tidak Sekolah', 'Tidak Sekolah'), ('SD/MI', 'SD/MI'), ('SMP/MTS', 'SMP/MTS'), ('SMA/MA/SMK', 'SMA/MA/SMK'), ('Diploma', 'Diploma'), ('S1', 'S1'), ('S2', 'S2'), ('S3', 'S3')], max_length=200, null=True)),
                ('pendapatanib', models.CharField(blank=True, choices=[('0 - 500.000', '0 - 500.000'), ('500.000 - 1.000.000', '500.000 - 1.000.000'), ('1.000.000 - 3.000.000', '1.000.000 - 3.000.000'), ('3.000.000 - 5.000.000', '3.000.000 - 5.000.000'), ('5.000.000 - 10.000.000', '5.000.000 - 10.000.000'), ('10.000.000 ++', '10.000.000 ++')], max_length=200, null=True)),
                ('nohpib', models.CharField(blank=True, max_length=200, null=True)),
                ('namawal', models.CharField(blank=True, max_length=200, null=True)),
                ('nikwal', models.CharField(blank=True, max_length=200, null=True)),
                ('statuswal', models.CharField(blank=True, choices=[('Masih Hidup', 'Masih Hidup'), ('Meninggal Dunia', 'Meninggal Dunia')], max_length=200, null=True)),
                ('alamatwal', models.CharField(blank=True, max_length=200, null=True)),
                ('pendidikanwal', models.CharField(blank=True, choices=[('Tidak Sekolah', 'Tidak Sekolah'), ('SD/MI', 'SD/MI'), ('SMP/MTS', 'SMP/MTS'), ('SMA/MA/SMK', 'SMA/MA/SMK'), ('Diploma', 'Diploma'), ('S1', 'S1'), ('S2', 'S2'), ('S3', 'S3')], max_length=200, null=True)),
                ('pendapatanwal', models.CharField(blank=True, choices=[('0 - 500.000', '0 - 500.000'), ('500.000 - 1.000.000', '500.000 - 1.000.000'), ('1.000.000 - 3.000.000', '1.000.000 - 3.000.000'), ('3.000.000 - 5.000.000', '3.000.000 - 5.000.000'), ('5.000.000 - 10.000.000', '5.000.000 - 10.000.000'), ('10.000.000 ++', '10.000.000 ++')], max_length=200, null=True)),
                ('nohpwal', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='kelassiswa',
            name='idkls',
        ),
        migrations.RemoveField(
            model_name='kelassiswa',
            name='nis',
        ),
        migrations.RenameField(
            model_name='siswa',
            old_name='nis',
            new_name='alamat',
        ),
        migrations.AddField(
            model_name='siswa',
            name='asal',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='siswa',
            name='jenla',
            field=models.CharField(blank=True, choices=[('Laki-Laki', 'Laki-Laki'), ('Perempuan', 'Perempuan')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='siswa',
            name='npm',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='siswa',
            name='status',
            field=models.CharField(blank=True, choices=[('Diterima', 'Diterima'), ('Ditolak', 'Ditolak')], max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Kelas',
        ),
        migrations.DeleteModel(
            name='Kelassiswa',
        ),
        migrations.AddField(
            model_name='ortu',
            name='npm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.siswa'),
        ),
    ]
