# Generated by Django 3.1.2 on 2021-07-24 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_auto_20210719_1137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siswa',
            old_name='username',
            new_name='user',
        ),
    ]
