# Generated by Django 3.1.2 on 2021-07-26 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_auto_20210724_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siswa',
            name='bulan',
            field=models.IntegerField(blank=True, choices=[('Januari', 'Januari'), ('Februari', 'Februari'), ('Maret', 'Maret'), ('April', 'April'), ('Mei', 'Mei'), ('Juni', 'Juni'), ('Juli', 'Juli'), ('Agustus', 'Agustus'), ('September', 'September'), ('Oktober', 'Oktober'), ('November', 'November'), ('Desember', 'Desember')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='siswa',
            name='tahun',
            field=models.IntegerField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='siswa',
            name='tanggal',
            field=models.IntegerField(blank=True, max_length=200, null=True),
        ),
    ]
