# Generated by Django 3.1.2 on 2021-07-31 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0014_auto_20210731_1056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dokumen',
            old_name='user',
            new_name='nama',
        ),
        migrations.RenameField(
            model_name='ortu',
            old_name='user',
            new_name='nama',
        ),
    ]
