# Generated by Django 3.1.2 on 2021-07-31 04:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data', '0016_remove_siswa_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dokumen',
            name='nama',
        ),
        migrations.RemoveField(
            model_name='ortu',
            name='nama',
        ),
        migrations.AddField(
            model_name='dokumen',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ortu',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
