# Generated by Django 3.1.2 on 2021-08-01 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0017_auto_20210731_1110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dokumen',
            name='user',
        ),
        migrations.RemoveField(
            model_name='ortu',
            name='user',
        ),
        migrations.AddField(
            model_name='dokumen',
            name='nama',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.siswa'),
        ),
        migrations.AddField(
            model_name='ortu',
            name='nama',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.siswa'),
        ),
        migrations.CreateModel(
            name='pengumuman',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=255)),
                ('pembayaran', models.CharField(blank=True, max_length=200, null=True)),
                ('lunas', models.BooleanField(default=False)),
                ('nama', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.siswa')),
            ],
        ),
    ]
