# Generated by Django 3.1.2 on 2021-08-01 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0018_auto_20210801_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pengumuman',
            name='pembayaran',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AlterField(
            model_name='pengumuman',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
