# Generated by Django 3.1.2 on 2021-08-03 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0019_auto_20210801_1349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dokumen',
            name='description',
        ),
        migrations.RemoveField(
            model_name='dokumen',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='dokumen',
            name='kk',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='dokumen',
            name='skl',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
