# Generated by Django 3.1.2 on 2021-08-08 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0020_auto_20210803_1015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dokumen',
            name='document',
        ),
        migrations.RemoveField(
            model_name='dokumen',
            name='kk',
        ),
        migrations.RemoveField(
            model_name='dokumen',
            name='skl',
        ),
        migrations.AddField(
            model_name='dokumen',
            name='ijazah',
            field=models.ImageField(blank=True, default='fotokosong.gif', upload_to=''),
        ),
        migrations.AddField(
            model_name='dokumen',
            name='nohpwal',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
