# Generated by Django 3.1.2 on 2021-08-08 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0021_auto_20210808_2035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dokumen',
            name='nohpwal',
        ),
        migrations.AddField(
            model_name='dokumen',
            name='kk',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='dokumen',
            name='skl',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='dokumen',
            name='ijazah',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
